### ISSUE TITLE
pdf generation failures

### ISSUE THREAD

**Issue by berger-n** [buda-base/buda-iiif-server#47] opened 2020-02-20 13:42 UTC
* cannot access to the volume listing page for bdr:W22084 ([link](https://iiif.bdrc.io/download/pdf/wi:bdr:W22084::bdr:I22084))

* can access to the volume listing page for bdr:W12827 ([link](http://iiif.bdrc.io/download/pdf/wi:bdr:W12827::bdr:I12827)) but then not to individual volume pdf download page eg Volume 9 ([link](http://iiif.bdrc.io/download/pdf/v:bdr:V12827_I2069::1-559)) 

* can access to individual volume pdf download page eg Volume 10 ([link](http://iiif.bdrc.io/download/pdf/v:bdr:V12827_I2070::1-547)) only after corresponding zip volume has been requested ([link](http://iiif.bdrc.io/download/zip/v:bdr:V12827_I2070::1-547))

**Comment by berger-n** [comment] 2020-02-20 17:19
> * can access to individual volume pdf download page eg Volume 10 ([link](http://iiif.bdrc.io/download/pdf/v:bdr:V12827_I2070::1-547)) only after corresponding zip volume has been requested ([link](http://iiif.bdrc.io/download/zip/v:bdr:V12827_I2070::1-547))

yet opening the pdf download link *sometimes* results in the following error message: `The link is wrong or has expired: please retry loading the archive and proceed to its download within 10 mn`

* actually in [bdr:W1PD8_0021](https://library.bdrc.io/show/bdr:W1PD8_0021) the behavior is that only first clicked of pdf/zip will open: if you click on pdf first it will work but then zip downloading will fail, if you click on zip first it will work but then pdf downloading will fail (previous error message in both cases)

* work parts *between* [root level](https://library.bdrc.io/show/bdr:W1PD8) and [leaf level](https://library.bdrc.io/show/bdr:W1PD8_0021) (eg [bdr:W1PD8_0019](https://library.bdrc.io/show/bdr:W1PD8_0019) and [bdr:W1PD8_0020](https://library.bdrc.io/show/bdr:W1PD8_0020)) will fail retrieving corresponding manifest (resp. [link1](https://iiifpres.bdrc.io/wvo:bdr:W1PD8_0019::bdr:V1PD8_I1PD82/manifest), [link2](https://iiifpres.bdrc.io/wvo:bdr:W1PD8_0020::bdr:V1PD8_I1PD84/manifest)); error 500 in both cases

**Comment by MarcAgate** [comment] 2020-02-26 13:39
Concerning the first message:

I was unable to reproduce the issues regarding volume 9 or 10. 
However in the first case ( https://iiif.bdrc.io/download/pdf/wi:bdr:W22084::bdr:I22084 ), we have a data issue:
Could not instantiate Identifier info for identifier:bdr:V22084_I0956 and the root cause is actually a data issue (see http://iiifpres.bdrc.io/il/v:bdr:V22084_I0956)

**Comment by MarcAgate** [comment] 2020-03-12 14:09
ok, all fixed as of commit 0c9f0fa

**Comment by MarcAgate** [comment] 2020-03-23 17:17
Done

**Closed** 2020-03-23 17:17 UTC
